### ISSUE TITLE
Rule proposal: prefer-optional-chaining

### ISSUE THREAD

**Issue by axetroy** [sindresorhus/eslint-plugin-unicorn#2434] opened 2024-08-23 19:35 UTC
### Description

for clean code

### Fail

```js
callback && callcak()
```

### Pass

```js
callback?.()
```

### Proposed rule name

prefer-optional-chaining

### Additional Info

Optional Chaining should have other scenarios, I will add them later

**Comment by sindresorhus** [comment] 2024-08-23 20:27
Duplicate of #429

**Closed** 2024-09-03 09:45 UTC
Labels: evaluating, new rule
