### ISSUE TITLE
no-array-method-this-argument false positive with Cypress.find

### ISSUE THREAD

**Issue by jase88** [sindresorhus/eslint-plugin-unicorn#1611] opened 2021-11-16 09:26 UTC
I get false-positives for the rule **no-array-method-this-argument** if using [find from cypress](https://docs.cypress.io/api/commands/find).

Strangely this only occurs if the argument for find is a separate variable, see example:
```js
const selector = 'another-selector';
// works fine
cy.get('#selector').find('another-selector', { timeout: 2000 });
// false positive
cy.get('#selector').find(selector, { timeout: 2000 });
```

![image](https://user-images.githubusercontent.com/804836/141957680-dfeae508-6a1c-4e8c-91ad-6e6267ab8189.png)

**Comment by fisker** [comment] 2021-11-16 11:35
We can analyze `selector`, if it's known not a `function`, ignore it.

**Comment by jase88** [comment] 2021-11-16 11:56
It is a fixed string like in the example. What do you mean with "ignore it"? eslint-disable-next-line?

Is it necessary to analyze selector? Shouldn't it be enough to check if find() was called from an array (and not from a Cypress Chainable context)? Sorry just my naive view 🙃

**Comment by dkMorlok** [comment] 2021-11-28 09:43
Same for me for code (second parameter is array):

```
return await this.persister.chats.find(accountId, [
	{ field: 'extId', value: values.extId },
])
```

**Comment by kidonng** [comment] 2022-09-02 12:48
Encountered the same issue with the [`fzf`](https://github.com/ajitid/fzf-for-js) package.

**Comment by fregante** [comment] 2024-02-10 09:07
Duplicate of https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1394

**Closed by fregante** 2024-02-10 09:07 UTC
Labels: bug
