### ISSUE TITLE
How can I define rule for folder?

### ISSUE THREAD

**Issue by zhaoyi0113** [sindresorhus/eslint-plugin-unicorn#777] opened 2020-06-19 11:18 UTC
Firstly, thanks a lot for releasing this awesome library. I am using it to enforce file name and below is my configuration:

```
"unicorn/filename-case": [
      "error",
      {
        "case": "camelCase"
      }
    ]
```

It works great for file name but I'd like to enforce folder name to be `snake_case`. Does it support folder name?

**Comment by sindresorhus** [comment] 2020-06-19 11:22
Duplicate of #686

**Closed by sindresorhus** 2020-06-19 11:22 UTC
