### ISSUE TITLE
prevent-abbreviations: How to avoid "e" matching "e2e"?

### ISSUE THREAD

**Issue by felixfbecker** [sindresorhus/eslint-plugin-unicorn#752] opened 2020-05-27 10:48 UTC
`prevent-abbreviations` has a replacement defined for `e` to `error` or `event`. Unfortunately, something like `e2e` also matches this replacement, e.g. a file like `e2e-test-utils.js`. The suggested replacements are then `error2error-test-utils.js` or `event2event-test-utils.js`, which don't make sense and would likely confuse people.

What I would like to do is define `e2e` as a replacement key, so that I can set it to `false` to simply allow `e2e` or define a replacement `end-to-end`. But right now, even if that is defined, it still matches the `e` replacement.
Could the logic be changed so that if the `e2e` matches, other replacements are not tried anymore? Maybe in the order they are defined, or ordered descending by their length (i.e. their specificity)

**Comment by sindresorhus** [comment] 2020-05-27 10:57
This is a bug. We should only do `e2` to `error2`, but not if anything comes after the number.

**Comment by fisker** [comment] 2020-05-27 10:58
duplicate of https://github.com/sindresorhus/eslint-plugin-unicorn/issues/567

**Comment by sindresorhus** [comment] 2020-05-27 10:59
I agree, we should prefer exact match, and then by specificity.

**Comment by felixfbecker** [comment] 2020-05-27 10:59
I don't think it's a duplicate - as I understand it, `whitelist` only works on the whole identifier. So putting `e2e` in the whitelist would not make it ignore `e2e-test-utils.js`

**Comment by fisker** [comment] 2020-05-27 11:01
Anyway I tried to fix this before, but can't come up with a good solution.

**Closed** 2020-12-09 12:39 UTC
Labels: bug, help wanted
