### ISSUE TITLE
[refer-global-this] if (typeof window === 'undefined')

### ISSUE THREAD

**Issue by tjx666** [sindresorhus/eslint-plugin-unicorn#2492] opened 2024-11-02 08:22 UTC
check `typeof globalThis === 'undefied'` is different with `typeof window === 'undefined'`

`unicorn/prefer-global-this`

```js
let clientQueryClientSingleton: QueryClient;
function getQueryClient() {
    if (typeof window === 'undefined') {
        // Server: always make a new query client
        return makeQueryClient();
    }
    // Browser: use singleton pattern to keep the same query client
    return (clientQueryClientSingleton ??= makeQueryClient());
}```

**Comment by fregante** [comment] 2024-11-04 17:37
Duplicate of https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2468

**Closed** 2024-11-04 17:37 UTC
Labels: bug
