### ISSUE TITLE
no-lonely-if: --fix deletes intervening comments

### ISSUE THREAD

**Issue by andersk** [sindresorhus/eslint-plugin-unicorn#953] opened 2020-12-22 10:52 UTC
Using `eslint --fix` with the `unicorn/no-lonely-if` rule can result in comments being unexpectedly deleted.

```js
if (
  foo
  // comment one
) {
  // comment two
  if (
    // comment three
    bar
    // comment four
  ) {
    baz();
  }
}
```

is fixed to

```js
if (
  foo && bar
  // comment one
) {
    baz();
  }
```

I would expect something more like

```js
if (
  foo &&
  // comment one
  // comment two
  // comment three
  bar
  // comment four
) {
  baz();
}
```

Configuration:

```json
{
  "plugins": ["unicorn"],
  "rules": {
    "unicorn/no-lonely-if": "error"
  }
}
```

Versions: `eslint@7.16.0`, `eslint-plugin-unicorn@24.0.0`

**Comment by fisker** [comment] 2020-12-22 10:59
This is by design, it's tested https://github.com/sindresorhus/eslint-plugin-unicorn/blob/582ca342b4f2587bb83eddf686a959d1ae940994/test/no-lonely-if.js#L93, but you can improve it if you like.

**Comment by andersk** [comment] 2020-12-22 11:08
A tested design bug that causes data loss is still a bug. The corresponding upstream [`no-lonely-if`](https://eslint.org/docs/rules/no-lonely-if) rule just refuses to automatically fix code with a comment between `else` and `if`, which would also be a reasonable strategy.

**Comment by fisker** [comment] 2020-12-22 11:13
It's still fixable, only need more effect, I don't think we should remove auto-fix for this reason.

**Comment by sindresorhus** [comment] 2020-12-22 11:39
I agree. It shouldn't auto-fix if it loses comments. Ideally, it should correctly move the comments. It doesn't even have to do it perfectly as long as it doesn't lose any comments.

**Comment by fisker** [comment] 2020-12-23 05:02
I'm not against to make the fix more safe, but if we are doing this, we need apply the strategy to all rules.

**Closed** 2021-01-29 18:48 UTC
Labels: enhancement, help wanted
