### ISSUE TITLE
Dependencies are missing and code throws in the last day or two

### ISSUE THREAD

**Issue by DavidAnson** [sindresorhus/eslint-plugin-unicorn#1105] opened 2021-02-17 16:35 UTC
This extension started crashing due to missing dependencies. For me, it’s @babel/core but in this project’s CI, it is other things. See the most recent run on main for examples: https://github.com/sindresorhus/eslint-plugin-unicorn/runs/1917420834?check_suite_focus=true

Not sure if unique to a specific rule, opening issue from phone.

Examples in CI for this project, “integration” step: https://github.com/sindresorhus/eslint-plugin-unicorn/runs/1917420834?check_suite_focus=true

**Comment by tiagoporto** [comment] 2021-02-17 17:07
After trying to install I'm getting  too many dependencies missing.

![Screen Shot 2021-02-17 at 1 58 00 PM](https://user-images.githubusercontent.com/3688905/108239059-44b0cc80-7128-11eb-92ea-fed5a22e3653.png)

After install  all required dependencies
- @babel/plugin-proposal-class-properties
- @babel/plugin-proposal-nullish-coalescing-operator
- @babel/plugin-proposal-optional-chaining
- @babel/preset-env
- @babel/preset-react
- @babel/preset-typescript
- babel-plugin-lodash

Now I'm getting

![Screen Shot 2021-02-17 at 2 04 57 PM](https://user-images.githubusercontent.com/3688905/108239942-23041500-7129-11eb-8231-4bb9b3218af5.png)

**Comment by tiagoporto** [comment] 2021-02-17 17:10
@DavidAnson Did you find a workaround for that?

**Comment by diogolessa** [comment] 2021-02-17 17:19
Same problem here, as related by @tiagoporto

**Comment by tiagoporto** [comment] 2021-02-17 17:38
My bad previous mentioned issue is not related.

**Comment by tiagoporto** [comment] 2021-02-17 18:03
Seems the issue is caused by the last `eslint-template-visitor` version, downgrade to `2.2.2` fixed the issue for me.

**Comment by codecog** [comment] 2021-02-17 23:33
```Error: Failed to load plugin 'unicorn' declared in '.eslintrc.js': [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,```

Experiencing the same issue here. When i remove `@babel/preset-typescript` from the config file, no errors.

**Comment by codecog** [comment] 2021-02-17 23:59
Can confirm @tiagoporto's comment. Downgrading `eslint-template-visitor` to `2.2.2` removes this error.

**Comment by futpib** [comment] 2021-02-18 04:25
Sorry guys, this should be fixed now on `eslint-template-visitor@2.3.2`. I somehow thought that `babel-eslint` to `@babel/eslint-parser` switch would be a minor change as Babel did not bump their version from 7 to 8 as they first intended.

**Closed** 2021-02-18 20:01 UTC
Labels: bug
