### ISSUE TITLE
support calver in package.json error

### ISSUE THREAD

**Issue by 9M6** [sindresorhus/eslint-plugin-unicorn#2319] opened 2024-04-11 19:50 UTC
I'm trying to use calver as my default versioning in my frontend app, but when I build the app it throws the error: `Invalid version: "2024.15"` 

N/A

```
Error: Failed to load plugin 'unicorn' declared in '.eslintrc » @nuxtjs/eslint-config-typescript » @nuxtjs/eslint-config': Invalid version: "2024.15"
    at Object.fixVersionField (/builds/confide-v2/frontend/node_modules/eslint-plugin-unicorn/node_modules/normalize-package-data/lib/fixer.js:191:13)
    at /builds/confide-v2/frontend/node_modules/eslint-plugin-unicorn/node_modules/normalize-package-data/lib/normalize.js:32:38
    at Array.forEach (<anonymous>)
    at normalize (/builds/confide-v2/frontend/node_modules/eslint-plugin-unicorn/node_modules/normalize-package-data/lib/normalize.js:31:15)
    at module.exports.sync (/builds/confide-v2/frontend/node_modules/eslint-plugin-unicorn/node_modules/read-pkg/index.js:37:36)
    at module.exports.sync (/builds/confide-v2/frontend/node_modules/eslint-plugin-unicorn/node_modules/read-pkg-up/index.js:27:24)
    at Object.<anonymous> (/builds/confide-v2/frontend/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:50:33)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
```

**Comment by fisker** [comment] 2024-04-12 06:14
You can open an issue on https://github.com/npm/normalize-package-data

**Comment by fregante** [comment] 2024-07-25 08:20
Duplicate of https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2019

**Closed by fregante** 2024-07-25 08:20 UTC
