### ISSUE TITLE
`prefer-spread` fixer bug

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#254] opened 2019-03-05 08:55 UTC
`prefer-spread` fixer has a bug on no-semi code style

error code like this

```js
const foo = []
Array.from(arr).forEach(doSomething)
```

will fix to code like

```js
const foo = []
[...arr].forEach(doSomething)
```

no semi added before `[` on second line, breaks code

**Comment by sindresorhus** [comment] 2019-03-05 09:17
This is exactly why you should use semicolons in JS...

**Comment by fisker** [comment] 2019-03-05 09:24
haha

but still a bug

**Comment by SamVerschueren** [comment] 2019-03-05 10:33
I don't think every rule should implement fallbacks in case the developer depends on ASI. I believe the rule works as intended and the semicolon should be inserted by either the `no-semicolon` (not sure if it exists though) rule which fixes this in case ASI fails or by something like prettier.

**Comment by fisker** [comment] 2019-03-05 11:08
I agree semicolon should insert by prettier, but source code already become 

```js
const foo = []
[...arr].forEach(doSomething)
```

prettier can't insert a semi before the second line.

**Comment by fisker** [comment] 2019-03-05 11:16
Maybe there is also a way to check previous Node(not sure is this called in the AST), to decide should add a extra `;` before `[`, I'm looking into it

**Comment by SamVerschueren** [comment] 2019-03-05 11:28
As said before, I don't agree that it should be fixed here because (a) Relying on ASI is controversial imo and (b) ESLint rule authors shouldn't care.

So even if a solution was found, I'm not sure I would be happy to see it land.

**Comment by fisker** [comment] 2019-03-05 12:34
I just find offical eslint rule `curly` also do a needs semicolon check to avoid SyntaxError, though it's different case to this one.

https://github.com/eslint/eslint/blob/5018378131fd5190bbccca902c0cf4276ee1581a/lib/rules/curly.js#L156

**Comment by fisker** [comment] 2019-07-06 06:57
`prefer-exponentiation-operator` may has the same problem

```js
const a = (()=>{})
Math.pow(-2, 2)
console.log(a)
```

fix to 

```js
const a = (()=>{})
(-2) ** 2
console.log(a)
```
code looks stupid, but still possible

**Comment by not-an-aardvark** [comment] 2019-07-06 07:09
Hi, the best place to report these issues is the [`eslint/eslint`](https://github.com/eslint/eslint) repository. Thanks!

**Comment by fisker** [comment] 2019-07-06 09:21
@not-an-aardvark  It's `unicorn/prefer-spread` rule  I reported, the reason  I mentioned you is because It's ASI problem and I found it's similar to your `curly` rule solution  and  hope  you can help

**Comment by MrHen** [comment] 2019-08-05 14:16
We should probably add a note to the documentation of the affected rules saying that they do not work properly if you don't use semicolons. People who use that style can then turn the rules off.

**Comment by fisker** [comment] 2019-08-08 03:28
agree

**Closed** 2020-03-05 13:29 UTC
