### ISSUE TITLE
[prevent-abbreviations] i18n expands to index18n

### ISSUE THREAD

**Issue by MasterEric** [sindresorhus/eslint-plugin-unicorn#1202] opened 2021-04-21 23:57 UTC
The phrase `i18n`, an abbreviation for `internationalization`, is used in code because using the word internationalization everywhere makes for unreadable code.

With the current version of the `unicorn/prevent-abbreviations`, the phrase `i18n` appears to be interpreted as `i`, then `18`, then `n`, in which the `i` is expanded to `index`.

The following configuration resolves the issue, but I think this is a common enough case to warrant a fix.

```
    'unicorn/prevent-abbreviations': [
      'warn',
      {
        ignore: ['i18n'],
      },
    ],
```

The problematic rule is `unicorn/prevent-abbreviations`.

Here is a code sample where the issue appears.

```js
const i18nData = { en: "Testing" };
```

**Comment by sindresorhus** [comment] 2021-04-22 05:58
Duplicate of #1188

**Closed by sindresorhus** 2021-04-22 05:58 UTC
Labels: bug
