### ISSUE TITLE
Error: Failed to load plugin 'eslint-plugin-unicorn' declared in '--config#overrides[2]': Cannot find module 'node:path'

### ISSUE THREAD

**Issue by SDAdham** [sindresorhus/eslint-plugin-unicorn#1851] opened 2022-07-03 09:44 UTC
Upgrading `eslint-plugin-unicorn` from `42.0.0` to `43.0.0` results in the following error:

```
@:~/> yarn lint
\ Processing: electron/src/preload.ts 

Oops! Something went wrong! :(

ESLint: 8.19.0

Error: Failed to load plugin 'eslint-plugin-unicorn' declared in '--config#overrides[2]': Cannot find module 'node:path'
Require stack:
- /node_modules/eslint-plugin-unicorn/rules/utils/rule.js
- /node_modules/eslint-plugin-unicorn/index.js
- /node_modules/@eslint/eslintrc/dist/eslintrc.cjs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/node_modules/eslint-plugin-unicorn/rules/utils/rule.js:2:14)
    at Module._compile (/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```
I reverted the version back and it worked

**Comment by dannobytes** [comment] 2022-07-13 18:03
Same here 😿

**Comment by erunion** [comment] 2022-07-13 18:15
This is happening because the library was bumped in v43 to require >= Node 14.18, where the `node:` protocol import syntax was introduced. If this is failing for you (as it is for us) it's because you're on an earlier version of Node.

**Comment by borjapazr** [comment] 2022-07-14 09:08
> This is happening because the library was bumped in v43 to require >= Node 14.18, where the `node:` protocol import syntax was introduced. If this is failing for you (as it is for us) it's because you're on an earlier version of Node.

With Node 15.x this problem also occurs 😢

**Comment by fisker** [comment] 2022-07-14 09:28
Closing since we are not going to do anything, please use a Node version that supports `require("node:path")`

**Closed by fisker** 2022-07-14 09:28 UTC

**Comment by Slapbox** [comment] 2022-09-13 20:08
Using Node 16.4.0 and seeing the error:

```
JSON Decode error: We expected JSON from 'eslint', but instead got this:
Error: Failed to load plugin 'unicorn' declared in '.eslintrc.js': Cannot find module 'node:path'
Require stack:
- /home/me/Documents/MyProject/node_modules/eslint-plugin-unicorn/rules/utils/rule.js
- /home/me/Documents/MyProject/node_modules/eslint-plugin-unicorn/index.js
- /home/me/Documents/MyProject/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
Referenced from: /home/me/Documents/MyProject/.eslintrc.js
```

I confirmed `node:path` is importable in this version by running `node -e 'console.log(typeof require("node:path"))'` which yields `object`. What could be the problem?

**Comment by SDAdham** [comment] 2022-09-23 13:07
I am actually on node 16 @fisker @erunion . not sure why this issue was closed and noone wanted to check with me which node i am on :)

**Comment by fisker** [comment] 2022-09-23 13:21
Node.js document that it's supported https://nodejs.org/dist/latest-v16.x/docs/api/modules.html#:~:text=Added%20node:%20import%20support%20to, if you are still facing this issue, please report to Node.js

**Comment by fisker** [comment] 2022-09-23 13:22
Or use an older version of `eslint-plugin-unicorn` https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1851#issuecomment-1245901674

**Comment by Slapbox** [comment] 2022-09-23 22:17
`require(node:path)` works fine on Linux, but `eslint-plugin-unicorn` does not, so I don't think the problem is Node.

**Comment by fisker** [comment] 2022-09-24 03:51
Can you setup a reproduce repo with GitHub actions?

**Comment by Slapbox** [comment] 2022-09-25 17:59
Sorry I have no experience with GitHub Actions, and I probably won't find time to make a repro for several weeks at least.

**Comment by Slapbox** [comment] 2022-09-27 20:54
But still, this issue should be open because it's a real issue.

**Comment by eviebutland** [comment] 2022-10-06 08:25
I am seeing this error when trying to add Typescript to Nuxt, in their documentation you install `@nuxtjs/eslint-config-typescript` which `eslint-plugin-unicorn` is a dependancy of https://typescript.nuxtjs.org/guide/lint/, using node **v16.17.1** 
<img width="579" alt="Screenshot 2022-10-06 at 09 25 35" src="https://user-images.githubusercontent.com/43405100/194261407-1109ff3c-a12b-42dc-b12d-12bb84b1ba05.png">

**Comment by Slapbox** [comment] 2022-10-06 20:26
@eviebutland what OS are you on?  I'm guessing Linux.

**Comment by eviebutland** [comment] 2022-10-07 07:53
@Slapbox , I am on Mac OS

**Comment by devzom** [comment] 2022-10-12 11:18
Try with this package:
`npm install eslint-plugin-node --save-dev`

**Comment by eviebutland** [comment] 2022-10-13 15:32
Spent a bit of time working around this, but got typescript enabled within our nuxt project without `@nuxtjs/eslint-config-typescript`. 

.eslintrc.js has -> 
```
parserOptions: {
    parser: '@typescript-eslint/parser'
  },

extends: [
    '@nuxtjs',
    'plugin:vue/recommended',
    'plugin:nuxt/recommended',
    'prettier'
  ],

overrides: [
    {
      files: ['*.ts'],
      parser: '@typescript-eslint/parser',
      plugins: ['@typescript-eslint'],
      extends: ['plugin:@typescript-eslint/recommended']
    }
  ],
```,

Since we are migrating from JS to TS we still need to allow both so have this within out tsconfig.json file -> 
```
"allowJs": true,
"noImplicitThis": false,
 "types": ["@types/node", "@nuxt/types"]
```

Now TS files and vue files with `script lang="ts"` lint correctly as well as normal vue files.

**Comment by DaddyChucky** [comment] 2022-10-16 23:18
In your package.json, simply change your versioning to accept upcoming minor & patch updates, that is by having:
`"version": "2.0.0"`
_instead of_
`"version": "2"`

**Comment by bilalq** [comment] 2022-10-28 22:43
Seeing this error on a fresh oclif generated app after running `npm update` and manually forcing eslint to upgrade to 8.x. I'm on MacOS running node 16.18.0.

**Comment by Slapbox** [comment] 2022-10-28 22:54
Just my two cents - it seems like all this suffering is not worth using `node:*` style require statements. We're still on an older version because of this issue. It really should not be closed as it's apparent that people whose machines meet the stated package requirements are having trouble with it on multiple machines.

**Comment by Slapbox** [comment] 2022-10-28 22:54
Just my two cents - it seems like all this suffering is not worth using node:* style require statements. We're still on an older version because of this issue. It really should not be closed as it's apparent that people whose machines meet the stated package requirements are having trouble with it on multiple machines. @fisker.

**Comment by fisker** [comment] 2022-10-29 02:18
We can't help if nobody can setup a bu reproduction.

**Comment by fisker** [comment] 2022-10-29 18:10
Benefit: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-node-protocol.md

**Comment by fisker** [comment] 2022-10-29 18:16
I don't really understand the issue here.
Is it that hard to setup a reproduction?
If many of you already have problems, can you just delete your private stuff and put your code somewhere, so I can debug.
I didn't even ask it has to be minimum.

**Comment by Slapbox** [comment] 2022-10-29 21:49
> If the Node.js version is the problem, why it's fine to stay on old Node.js version, but not fine to stay on old unicorn version?

That's not the case. Node.js 16.17.0 was released 2 months ago... I'll look into making a repro, but the stated benefit seems absolutely trivial in `eslint-plugin-unicorn`'s own code, even if it has more notable benefits in larger codebases.

**Comment by Slapbox** [comment] 2022-10-29 22:07
Can't reproduce it now with the same Node version, same eslint-plugin-unicorn version, and same ESLint version, same config. Who knows what the problem was. Seems very clear the bug was not in Node itself though.

Although that resolves this issue for me, I still don't believe that the `node:` requires are worth the trouble they've caused here - but that's not my decision to make.

**Comment by BBosman** [comment] 2022-11-28 09:14
I'm seeing the same issue, but with a twist. It works on my local dev (Mac) machine, but fails on our CI (Windows) machine.

As can be seen below, it's running Node 16.

I'm downgrading to version 42 to solve it for now, but wanted to leave this here to help with the root cause investigation.

```
; node bin location = E:\_work\_tool\node\16.18.1\x64\node.exe
; node version = v16.18.1
; npm local prefix = E:\_work\237\s
; npm version = 8.19.2
; cwd = E:\_work\237\s
; HOME = C:\Windows\ServiceProfiles\NetworkService
; Run `npm config ls -l` to show all defaults.
C:\Windows\system32\cmd.exe /D /S /C "E:\_work\_tool\node\16.18.1\x64\npm.cmd start lint"


Oops! Something went wrong! :(

> nps lint
ESLint: 8.28.0


nps is executing `lint` : nps lint.eslint && nps lint.scss
Error: Failed to load plugin 'unicorn' declared in '.eslintrc.json': Cannot find module 'node:path'
nps is executing `lint.eslint` : eslint --cache "src/**/*.ts" "test/**/*.ts" "*.js" "customplugins/**/*.js"
Require stack:
- E:\_work\237\s\node_modules\eslint-plugin-unicorn\rules\utils\rule.js
- E:\_work\237\s\node_modules\eslint-plugin-unicorn\index.js
- E:\_work\237\s\node_modules\@eslint\eslintrc\dist\eslintrc.cjs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (E:\_work\237\s\node_modules\eslint-plugin-unicorn\rules\utils\rule.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
```

**Comment by loganadin-bhuvanaganesan** [comment] 2023-02-15 05:53
After updating to node 16 it started work

**Comment by gadzhimagomedov81** [comment] 2023-02-27 09:48
eslint should run with node version 16. This worked for me

**Comment by shrpne** [comment] 2023-04-05 09:02
`rm -rf node_modules && rm package-lock.json && npm i` solved it for me

**Comment by tarikkavaz** [comment] 2023-08-15 06:57
> `rm -rf node_modules && rm package-lock.json && npm i` solved it for me

that worked for me too (node 16.13.0)
