### ISSUE TITLE
[filename-case] error for file name with exact name the rule suggests.

### ISSUE THREAD

**Issue by kalbert312** [sindresorhus/eslint-plugin-unicorn#430] opened 2019-11-07 15:33 UTC
Hello. Today I received some strange error related to filename-case:

On the left: create-react-app `npm run start`, On the right: `npm run lint` -> `eslint 'src/**/*.{js,jsx,ts,tsx}'`
I'm using the `EXTEND_ESLINT=true` flag for create-react-app.
![Screen Shot 2019-11-07 at 10 31 36 AM](https://user-images.githubusercontent.com/5498623/68402759-d53ce680-0149-11ea-8fc5-7dae773dae0a.png)
This was after a rename of the file from `queryParamUtil.ts` to `query-param-util.ts`
Versions:
```
		"eslint": "^6.6.0",
		"eslint-plugin-unicorn": "^12.1.0",
```
What could be going on?

**Comment by fisker** [comment] 2019-11-08 08:15
can't reproduce, I ran test on `src/util/query-param-util.ts` passed, have you set options on this rule?

**Comment by fisker** [comment] 2019-11-08 08:25
I also test with options: `{cases: {kebabCase: true, pascalCase: true}}`,

`queryParamUtil.ts` got

``Filename is not in kebab case or pascal case. Rename it to `query-param-util.ts` or `QueryParamUtil.ts` ``

and `query-param-util.ts` no error

**Comment by kalbert312** [comment] 2019-11-08 14:42
Options are kebab case and pascal case. Even if I rename the still to something else (`query-params.ts`), the error suggests renaming it to `query-param-util.ts` or `queryParamUtil.ts`, but only during create-react-app dev. ESLInt on the command line works fine. Still trying to debug it.
![Screen Shot 2019-11-08 at 9 42 25 AM](https://user-images.githubusercontent.com/5498623/68484852-1eee0580-020c-11ea-8816-7328b3a18793.png)

**Comment by fisker** [comment] 2019-11-08 15:22
How this even possible... there must be something wrong, good luck

**Comment by kalbert312** [comment] 2019-11-08 15:25
Beats me... I just ended up disabling it.

**Comment by fisker** [comment] 2019-11-14 07:24
can we close this?

**Comment by kalbert312** [comment] 2019-11-15 21:22
I guess. It's no longer affecting me but I never determined what the cause was.

**Closed** 2019-11-16 00:15 UTC
