### ISSUE TITLE
`no-for-loop` auto-fix tries to use `.entries()` on a string (which doesn't exist)

### ISSUE THREAD

**Issue by Miodec** [sindresorhus/eslint-plugin-unicorn#1941] opened 2022-10-27 10:41 UTC
The auto-fix for `no-for-loop` seems to be not working well with strings. The code:
```ts
for (let c = 0; c < historyWord.length; c++) {
  ...
}
```
quick fix converts it to:
```ts
for (const [c, element] of historyWord.entries()) {
  ...
}
```

which is causing a typescript error:
```
Property 'entries' does not exist on type 'string'.ts(2339)
```

If we want to use `.entries()` here, we should spread the string:
```ts
for (const [c, element] of [...historyWord].entries()) {
  ...
}
```

This satisfies the rule and typescript, and might close issues #1836 and #1802

**Comment by sindresorhus** [comment] 2022-10-27 11:11
There's no way to statically know that `historyWord` is a string, unless it's defined in the same scope, or by using the TypeScript type info.

**Comment by Miodec** [comment] 2022-10-27 11:47
In my case, it is in the same scope

General structure of my code:
```ts

const historyWord: string = "i am defined here!"

if (historyWord == word) {
  //...
} else if (historyWord.length >= word.length) {
  for (const [c, element] of [...historyWord].entries()) {
    //...
  }
}
```

I think if it is possible to know that its a string, the fix should be appropriately different.

**Comment by fregante** [comment] 2023-01-28 07:02
Duplicate of https://github.com/sindresorhus/eslint-plugin-unicorn/issues/738

**Closed** 2023-01-28 07:06 UTC
Labels: bug, help wanted
