### ISSUE TITLE
rules not found

### ISSUE THREAD

**Issue by zilahir** [sindresorhus/eslint-plugin-unicorn#858] opened 2020-10-13 18:44 UTC
![image](https://user-images.githubusercontent.com/6687149/95902220-29f6d180-0d9d-11eb-9551-80d4f9656e25.png)

This is not the first time i am experiencing this, and maybe I am just missing some fundamental logic. Some rules, sometimes, are `not found`.

```
 Line 34:2:  Definition for rule 'unicorn/no-null' was not found  unicorn/no-null
 Line 1:1:   Definition for rule 'unicorn/no-nested-ternary' was not found  unicorn/no-nested-ternary
```

my `eslintconfig` is the following: 

```
{
...
"extends": [
		"@zilahir/eslint-config/react",
		"plugin:jsdoc/recommended",
		"plugin:jest/recommended",
		"plugin:unicorn/recommended"
	],
...
}
```

And the related `package.json`: 

```
{
...
"devDependencies": {
		"@babel/core": "^7.8.0",
		"@types/classnames": "^2.2.10",
		"@types/react-datepicker": "^2.11.1",
		"@types/react-lazy-load-image-component": "^1.3.0",
		"@types/react-redux": "^7.1.9",
		"@typescript-eslint/eslint-plugin": "^2.28.0",
		"@typescript-eslint/parser": "^2.28.0",
		"@zilahir/eslint-config": "^3.0.0",
		"@zilahir/prettier-config": "^1.0.2",
		"@zilahir/stylelint-config": "^3.0.0",
		"eslint-config-airbnb": "^17.1.1",
		"eslint-config-prettier": "^6.9.0",
		"eslint-plugin-import": "^2.20.0",
		"eslint-plugin-jest": "^23.13.1",
		"eslint-plugin-jsdoc": "^22.0.0",
		"eslint-plugin-jsx-a11y": "^6.2.3",
		"eslint-plugin-react": "^7.17.0",
		"eslint-plugin-unicorn": "^22.0.0",
		"prettier": "1.19.1",
		"stylelint": "^10.1.0",
	},
...
}
```

Any idea what am i missing here? 

Thank you!

**Comment by fisker** [comment] 2020-10-14 02:21
Can you run 

```bash
node -p "require('eslint-plugin-unicorn/package.json').version"
node -p "require.resolve('eslint-plugin-unicorn')"
```

**Comment by zilahir** [comment] 2020-10-14 09:10
hi @fisker ! 

```
➜  ████ git:(XES-459) node -p "require('eslint-plugin-unicorn/package.json').version"
22.0.0
```

```
➜  ████ git:(XES-459) node -p "require.resolve('eslint-plugin-unicorn')"
/Users/richardzilahi/work/xenon/node_modules/eslint-plugin-unicorn/index.js
```

>And is it possible that you're running a global installed ESLint?

This was also my idea, but no, or at least as far as i can tall, it's launched from the project.

**Comment by fisker** [comment] 2020-10-14 10:02
Sorry, can't help

**Comment by MeloncholyShiro** [comment] 2020-10-14 11:42
Yep i have this bug too

**Comment by zilahir** [comment] 2020-10-14 13:34
@MeloncholyShiro would you mind sharing your `package.json` ?

**Comment by MeloncholyShiro** [comment] 2020-10-14 14:26
@zilahir `"dependencies": {
		"@testing-library/jest-dom": "^4.2.4",
		"@testing-library/react": "^9.5.0",
		"@testing-library/user-event": "^7.2.1",
		"@types/jest": "^24.9.1",
		"@types/node": "^12.12.67",
		"@types/react": "^16.9.51",
		"@types/react-dom": "^16.9.8",
		"clsx": "^1.1.1",
		"date-fns": "^2.16.1",
		"dinero.js": "^1.8.1",
		"nanoid": "^3.1.12",
		"node-sass": "^4.14.1",
		"normalize.css": "^8.0.1",
		"react": "^16.13.1",
		"react-dom": "^16.13.1",
		"react-redux": "^7.2.1",
		"react-scripts": "3.4.3",
		"redux": "^4.0.5",
		"typescript": "^3.7.5"
	},
	"devDependencies": {
		"@types/dinero.js": "^1.6.5",
		"@typescript-eslint/eslint-plugin": "^4.4.0",
		"babel-eslint": "^10.1.0",
		"eslint-config-airbnb-typescript": "^11.0.0",
		"eslint-config-prettier": "^6.11.0",
		"eslint-plugin-import": "^2.22.0",
		"eslint-plugin-jsx-a11y": "^6.3.1",
		"eslint-plugin-no-use-extend-native": "^0.5.0",
		"eslint-plugin-optimize-regex": "^1.2.0",
		"eslint-plugin-promise": "^4.2.1",
		"eslint-plugin-react": "^7.21.0",
		"eslint-plugin-react-hooks": "^4.1.2",
		"eslint-plugin-sonarjs": "^0.5.0",
		"eslint-plugin-unicorn": "^22.0.0",
		"husky": "^4.3.0",
		"lint-staged": "^10.4.0",
		"prettier": "^2.1.2"
	}`

**Comment by zilahir** [comment] 2020-10-14 16:02
@MeloncholyShiro the parts which i am interested in is actually not visible. is this project of yours bootstrapped with `create-react-app`? If so, is there a `"eslintConfig"` entry in it?

**Comment by MeloncholyShiro** [comment] 2020-10-14 16:05
@zilahir all parts, all eslint-disable unicorn------ returns error. Yes, i have:
![изображение](https://user-images.githubusercontent.com/44039577/96015402-36883200-0e50-11eb-8f12-2db3794e04db.png)

And .eslintrc: 
![изображение](https://user-images.githubusercontent.com/44039577/96015477-4869d500-0e50-11eb-8c40-f243542c1513.png)

**Comment by zilahir** [comment] 2020-10-14 19:11
@MeloncholyShiro remove the `extends` from your package json, restart the IDE, and see if your problem still persists.

**Comment by zilahir** [comment] 2020-10-16 13:19
@MeloncholyShiro any success?

**Comment by MeloncholyShiro** [comment] 2020-10-16 13:44
@zilahir  Yep, it fixed this stuff :)

**Comment by MeloncholyShiro** [comment] 2020-10-16 14:13
@zilahir Oops, not fixed, again this stuff 
![изображение](https://user-images.githubusercontent.com/44039577/96269324-e9809900-0fd2-11eb-9993-374bf89bde96.png)

**Comment by fisker** [comment] 2020-10-16 14:19
Can you create a reproducible test repo

**Comment by fisker** [comment] 2020-10-21 02:24
Can you run `eslint` with `--debug` flag?

**Comment by kkmuffme** [comment] 2020-10-27 12:46
@MeloncholyShiro I had the exact same issue. Perhaps my solution works for you too? https://github.com/sindresorhus/eslint-plugin-unicorn/issues/871#issuecomment-711167331 (if you are not in a global install, you can also just manually supply the path instead of a variable)

**Comment by MeloncholyShiro** [comment] 2020-10-27 13:47
@kkmuffme I fix this by update all my eslint-dep, and eslint as same. + Remove global installed eslint.

**Comment by sindresorhus** [comment] 2021-01-11 08:24
Closing as it doesn't look like this is an issue with this project. Feel free to continue discussing even though the issue is closed.

**Closed by sindresorhus** 2021-01-11 08:24 UTC
Labels: bug
