### ISSUE TITLE
Autofix breaks regex

### ISSUE THREAD

**Issue by Slapbox** [sindresorhus/eslint-plugin-unicorn#1505] opened 2021-08-28 22:31 UTC
Automatic conversion of non-capturing group to character grouping converts `.` _operator_ to `.` _character_.

**Affected rule:** `unicorn/better-regex`

```js
const before = /(?:.|\n)/;
```

```js
const after = /[.\n]/;
```

If someone knows what dependency is responsible for this behavior, let me know and I'll go open an issue there. Until then, this seemed best.

**Comment by sindresorhus** [comment] 2021-08-28 22:57
https://github.com/DmitrySoshnikov/regexp-tree/issues/227

**Comment by sindresorhus** [comment] 2021-08-28 22:58
Duplicate of https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1231

**Closed by sindresorhus** 2021-08-28 22:58 UTC
Labels: bug
