### ISSUE TITLE
[Bug] Invalid shorthand fix

### ISSUE THREAD

**Issue by KostiantynKopytov** [sindresorhus/eslint-plugin-unicorn#478] opened 2019-12-17 09:00 UTC
`/^[-0-9a-z]+$/i` is replaced with `/^[\d-a-z]+$/i` by moving first dash after \d it breaks it.

**Comment by futpib** [comment] 2019-12-17 11:25
This looks like a duplicate of #472.

@KostiantynKopytov if that's not the case, please explain why and we'll reopen.

**Closed by futpib** 2019-12-17 11:25 UTC
