### ISSUE TITLE
[no-array-for-each] `for...of` not faster than `some`/`forEach`/`fori`

### ISSUE THREAD

**Issue by SettingDust** [sindresorhus/eslint-plugin-unicorn#1983] opened 2022-11-19 12:38 UTC
According to the benchmark https://www.measurethat.net/Benchmarks/Show/537/0/for-vs-foreach-vs-some-vs-forof#latest_results_block

`for...of` is slower that any others. The "Faster" isn't correctly. This rule should probably not be enabled by default

**Comment by zloirock** [comment] 2022-11-19 12:55
Perfect test -)

Try, for example, `new Array(100).forEach(console.log)` in your browser console - it does not work with holes.

Even in case if you will fix it, without mutation of any observable state, you just test what dead code will be removed.

Please keep this in mind when writing tests in the future ;-)

However, I agree that "faster" is not a correct argument - that depends on optimizations from the implementation, too ofter `for-of` is slower.

**Comment by sindresorhus** [comment] 2022-11-19 13:22
Duplicate of #1522

**Closed by sindresorhus** 2022-11-19 13:22 UTC
