### ISSUE TITLE
better-regex proposes to replace (.|[\r\n]) with [.\r\n]

### ISSUE THREAD

**Issue by urchick** [sindresorhus/eslint-plugin-unicorn#1231] opened 2021-04-28 14:27 UTC
`better-regex` rule proposes to replace `(.|[\r\n])` with `[.\r\n]` which is wrong because `.` behaves literally in character class

**Comment by sindresorhus** [comment] 2021-04-28 17:37
Can you also report this over at https://github.com/DmitrySoshnikov/regexp-tree? Which is the package we use that does the actual regex optimizations.

**Comment by urchick** [comment] 2021-04-28 21:52
sure

https://github.com/DmitrySoshnikov/regexp-tree/issues/227#issue-870417115

**Comment by Slapbox** [comment] 2021-08-28 23:35
I think this rule should not be included in `unicorn/recommended` until the issue is addressed in `regexp-tree`, or users should be warned of the bug, especially since the description includes making RegExps "safer."

Also, minor correction to the title; it should read: "better-regex proposes to replace (.|[\r\n]) with ([.\r\n])" - just tested it.

**Comment by Maxim-Mazurok** [comment] 2023-03-18 23:48
Running into the same issue, suggests to replaces `(.|\s)` with `[.\s]` which doesn't work

**Comment by Slapbox** [comment] 2023-03-19 00:22
@Maxim-Mazurok you should probably create a new issue for that and link to this one from there.

**Comment by Maxim-Mazurok** [comment] 2023-03-19 01:05
@Slapbox but I think it's the same issue basically... The `.` isn't considered to have different meaning depending on the context.

**Comment by Slapbox** [comment] 2023-03-19 01:40
You can see that (at least as of my last test) OP's regex is not transformed quite the same way as yours - the title was wrong.

> Also, minor correction to the title; it should read: "better-regex proposes to replace (.|[\r\n]) with ([.\r\n])" - just tested it.

**Comment by Slapbox** [comment] 2023-03-19 01:41
Fwiw we don't use this rule because it's broken, has been for years, and presumably will be for a long time to come. Enabling the rule only caused pain here.

**Comment by Maxim-Mazurok** [comment] 2023-04-09 03:40
> Can you also report this over at [DmitrySoshnikov/regexp-tree](https://github.com/DmitrySoshnikov/regexp-tree)? Which is the package we use that does the actual regex optimizations.

I believe this to be the same as https://github.com/DmitrySoshnikov/regexp-tree/issues/227

And there's a PR to fix it: https://github.com/DmitrySoshnikov/regexp-tree/pull/254 (I've used OP's case in test cases for PR)

**Comment by fregante** [comment] 2024-02-10 10:12
The PR was merged, this was presumably fixed

**Closed by fregante** 2024-02-10 10:12 UTC
Labels: bug
