### ISSUE TITLE
Rule proposal: `no-useless-nesting-in-template-literals`

### ISSUE THREAD

**Issue by B2o5T** [sindresorhus/eslint-plugin-unicorn#1652] opened 2021-12-21 13:51 UTC
### Description

Reports nested instances of a string or a template literal. Suggests inlining the nested instances into the containing template string.
inspired by JetBrains https://www.jetbrains.com/help/phpstorm/javascript-and-typescript-redundant-nesting-in-template-literal.html

### Fail

```js
`Hello, ${`Brave ${"New"}`} ${"World"}!`

`${2021} year!`

`${true} or ${false}`

`${String(someVar)} foo` // redundant call String as .toString() will be applied automatically
```

### Pass

```js
`Hello, Brave New World!`

`2021 year!`

`true or false`

`${someVar} foo`
```

**Comment by sindresorhus** [comment] 2021-12-21 14:12
For consistency, it should be called `no-useless-nesting-in-template-literals` (also note the `s` at the end)

**Comment by fisker** [comment] 2021-12-22 01:23
Is this duplicate of #1261?

**Closed** 2021-12-22 02:03 UTC
Labels: evaluating, new rule
