### ISSUE TITLE
Can not ignore unicorn/no-null in some case 

### ISSUE THREAD

**Issue by yoyo837** [sindresorhus/eslint-plugin-unicorn#703] opened 2020-04-30 13:31 UTC
.eslintrc.js: rules `'unicorn/no-null': 0,`

code (Note the line of code marked `FIXME`): 

```jsx
// import 'core-js/stable';
// import 'regenerator-runtime/runtime';
import uniq from 'lodash/uniq';
import React from 'react';
import ReactDom from 'react-dom';
import { createStore, combineReducers, applyMiddleware, compose } from 'redux';
import { Provider } from 'react-redux';
import { createBrowserHistory } from 'history';
import { ConnectedRouter, connectRouter, routerMiddleware } from 'connected-react-router';
import createSagaMiddleware from 'redux-saga';

import modelManager, { getReducer, getSaga, SHOW, HIDE } from '@/models';
import initRequest from '@/utils/request';
import App from '@/routes/App';

const history = createBrowserHistory();

// Build the middleware for intercepting and dispatching navigation actions
const reduxRouterMiddleware = routerMiddleware(history);
const reduxSagaMiddleware = createSagaMiddleware();

// window.__REDUX_DEVTOOLS_EXTENSION__
// const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
//   //
// }) || compose
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
const connectRouterReducer = connectRouter(history);

const allModelKeys = modelManager.keys();

const injectedModels = [];
const loadModels = keys => {
  injectedModels.push(
    ...uniq(keys)
      .filter(key => !injectedModels.some(m => m.namespace === key) && allModelKeys.includes(key))
      .map(key => {
        const model = modelManager.load(key);
        if (model == null) { // **FIXME target line 1** 
          throw new Error(`[${key}]: Model load fails`);
        }
        return model.default || model;
      })
      .filter(Boolean)
  );
};

// redux 初始化默认加载的model
const initialModels = ['global', 'login', 'user', 'venue', 'datatable', 'extfield'];

loadModels(initialModels);

const createNewReducers = () => {
  const reducers = {};
  injectedModels.forEach(model => {
    reducers[model.namespace] = getReducer(model);
  });
  return combineReducers({
    ...reducers,
    loading: (state, action) => {
      switch (action.type) {
        case SHOW:
        case HIDE:
          return {
            ...state,
            effects: {
              ...state.effects,
              [action.payload.actionType]: action.type === SHOW,
            },
          };
        default:
          return state || {};
      }
    },
    router: connectRouterReducer,
  });
};

const runSaga = (keys = [], hasLoadKeys = []) => {
  injectedModels
    .filter(model => keys.includes(model.namespace) && !hasLoadKeys.includes(model.namespace))
    .forEach(model => {
      reduxSagaMiddleware.run(getSaga(model));
    });
};

const store = createStore(
  createNewReducers(),
  // preloadedState
  {
    loading: {
      effects: {},
    },
  },
  composeEnhancers(
    applyMiddleware(
      reduxRouterMiddleware,
      // promiseMiddleware
      // eslint-disable-next-line unicorn/consistent-function-scoping
      () => next => action => {
        const { type } = action;
        if (typeof type === 'string') {
          const [namespace, effectName] = type.split('/');
          // model.effects 的一定都是 effect
          if (
            injectedModels
              .filter(model => model.namespace === namespace)
              .some(model => model.effects && model.effects[effectName])
          ) {
            return new Promise((resolve, reject) => {
              next({
                ...action,
                _resolve: resolve,
                _reject: reject,
              });
            });
          }
        }
        return Promise.resolve(next(action));
      },
      reduxSagaMiddleware
    )
  )
);

initRequest(store.dispatch, store);

runSaga(initialModels, []);

const appManager = {
  injectModel: model => {
    if (model == null || model.length === 0) { // **FIXME target line 2**
      return;
    }
    const hasLoadKeys = injectedModels.map(m => m.namespace);
    loadModels(model);
    store.replaceReducer(createNewReducers());
    runSaga(model, hasLoadKeys);
  },
};

ReactDom.render(
  <Provider store={store}>
    <ConnectedRouter history={history}>
      <App app={appManager} />
    </ConnectedRouter>
  </Provider>,
  // eslint-disable-next-line unicorn/prefer-query-selector
  document.getElementById('root')
);

```

It report 

![image](https://user-images.githubusercontent.com/6134547/80715864-8cc71a00-8b29-11ea-869c-224bc7a853b0.png)

If I fix any one error, the other will no longer report the error.

**Comment by papb** [comment] 2020-04-30 14:00
Hi, can you try to create a smaller example? I doubt all these lines are necessary to reproduce the issue. Making it a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) will save time from maintainers and increase the odds you get a faster response.

**Comment by fisker** [comment] 2020-04-30 14:40
the `==` should be auto-fixable, if it's `===` should be ignored by default

**Comment by fisker** [comment] 2020-04-30 14:43
Question, why don't you want fixed to `undefined`? They are equal

**Comment by kevinoid** [comment] 2020-05-29 22:31
One reason it might be preferable to allow `== null` as a special case is that the built-in [`eqeqeq` rule](https://eslint.org/docs/rules/eqeqeq) has options ([`smart`](https://eslint.org/docs/rules/eqeqeq#smart) and [`"always", {"null": "ignore"}`](https://eslint.org/docs/rules/eqeqeq#always), [used by airbnb](https://github.com/airbnb/javascript/blob/eslint-config-airbnb-v18.1.0/packages/eslint-config-airbnb-base/rules/best-practices.js#L44)) to allow `x == null`, but no similar option to allow `x == undefined` (see eslint/eslint#13303).

**Comment by kevinoid** [comment] 2020-05-29 22:35
Note: `x == null` is a shorthand for `x === null || x === undefined`.  I'm not advocating for or against supporting it, just came across this issue while considering it.

**Comment by fisker** [comment] 2020-06-01 06:32
@kevinoid 

Thank you for your explanation. 

I think this is a bug in eslint, `if (foo == null)` is equals to `if (foo == undefined)`, why allow `null`, but not allow `undefined`.

anyway, since that `eqeqeq` is not going to change, I'm adding an option to ignore `==` and `!=` on our side.

**Comment by sindresorhus** [comment] 2021-01-11 08:38
Per https://github.com/sindresorhus/eslint-plugin-unicorn/pull/757#issuecomment-636652272, this should be fixed in ESLint. Open an issue on ESLint about this.

**Closed by sindresorhus** 2021-01-11 08:38 UTC
